[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Daily 12:00 UTC (adjust for your local 7am if needed)
[[scheduled.functions]]
  path = "morning-brief"
  cron = "0 12 * * *"
